  language: "zh"

  pipeline:
  - name: "tokenizer_jieba"
    dictionary_path: "dictionary"
  - name: "bert_vectors_featurizer"
    ip: '192.168.1.75'
    port: 7555
    port_out: 7556
    show_server_config: True
    timeout: 50000
  #- name: "active_bert_nerual_classifier"
  - name: "intent_estimator_classifier_tensorflow_embedding_bert"
  #- name: "nlp_spacy"
  - name: "intent_entity_featurizer_regex"
  #- name: "ner_bilstm_crf_estimator"
  - name: "ner_bilstm_crf"
  - name: "ner_synonyms"
  #- name: "ner_duckling_http"
  #  dimensions: [
  #              "number",
  #              "phone-number",
  #              "time"
  #          ]
  #  url: 'http://localhost:8000'
  #  locale: 'zh_CN'
  #  timezone: 'Asia/Shanghai'
  #- name: "ner_regex_entity"
  #  #regexs: ['([1-9]\d{5}(18|19|([23]\d))\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{3}[0-9Xx]$)|(^[1-9]\d{5}\d{2}((0[1-9])|(10|11|12))(([0-2][1-9])|10|20|30|31)\d{2}[0-9Xx])']
  #  startusing: True
